In [1]:
import pandas as pd
import numpy as np

In [2]:
dat = pd.read_csv('/home/achyutganti/Documents/myPython/ML Class/Neural_Ntwrk/train.csv')
data = pd.DataFrame(dat)

In [69]:
data.shape

(40000, 785)

In [3]:
labels = data.iloc[:,0]
labels.shape

(40000,)

In [4]:
dataj = data.drop(['label'],axis=1)
dataj.shape

(40000, 784)

In [5]:
# just select first 50 rows from the the dataset and the labels dataset
data_s = dataj.iloc[:50,]
data_s.shape
# labels too
labels_s = labels.iloc[:50,]
labels_s.shape

(50,)

In [ ]:
def normalise(data):
    for

In [7]:
# create a dummy for the variables 
def dummy(df):
    dff = pd.get_dummies(df)
    return dff

In [8]:
dummy_labels = dummy(labels_s)

In [13]:
# my dataset is data_s and labels_s
#initialize weights 
input_weights = np.random.rand(25,784)*0.1

# output weights
output_weights= np.random.rand(10,25)*0.1

#input bias unit
input_bias_unit = np.ones((len(data_s),1))
output_bias_unit = np.ones((len(data_s),1))

# input bias_weights
input_bias_weight = np.random.rand(1,25)*0.1
# output bias_weights 
output_bias_weight = np.random.rand(1,10)*0.1

In [76]:
# function for sigmoid function
def sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

In [77]:
# forward propogation. And this goes into a function

hidden_values = np.dot(np.c_[input_bias_unit,data_s],np.c_[input_bias_weight.transpose(),input_weights].transpose())
sigmoid_hidden_values = sigmoid(hidden_values)
output_values= np.dot(np.c_[output_bias_unit,sigmoid_hidden_values],np.c_[output_bias_weight.transpose(),output_weights].transpose())
output_sigmoid_values = sigmoid(output_values)
output_sigmoid_values.shape

(50, 10)

In [15]:
# total error of the system
total_error = (dummy_labels - output_sigmoid_values)**2/2

In [84]:
# calculate the error for the output unit
output_error = output_sigmoid_values*(1-output_sigmoid_values)*(dummy_labels-output_sigmoid_values)

In [16]:
# hidden layer error
hidden_layer_error = sigmoid_hidden_values*(1-sigmoid_hidden_values)*np.dot(output_error,output_weights)
hidden_layer_error

NameError: name 'sigmoid_hidden_values' is not defined

In [ ]:
# updating the weights
output_weight+ 0.5*np.dot()

In [53]:
output_error.shape

(50, 10)

In [54]:
output_bias_weight.shape

(1, 10)

In [61]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

In [83]:
sigmoid_hidden_values

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [86]:
hidden_values = np.dot(np.c_[input_bias_unit,data_s],np.c_[input_bias_weight.transpose(),input_weights].transpose())
hidden_values.shape

(50, 25)

In [12]:
input_weights

array([[ 0.00255655,  0.02657079,  0.08811456, ...,  0.0776645 ,
         0.0230019 ,  0.00757169],
       [ 0.04991298,  0.05411739,  0.07771779, ...,  0.00025026,
         0.02700583,  0.02277223],
       [ 0.00494159,  0.05287234,  0.09025866, ...,  0.00825993,
         0.02894685,  0.06383467],
       ..., 
       [ 0.02704161,  0.06174772,  0.07813285, ...,  0.02071187,
         0.08431289,  0.02430257],
       [ 0.03620273,  0.00608956,  0.00720855, ...,  0.0945274 ,
         0.07472458,  0.00665918],
       [ 0.02023986,  0.03961718,  0.08787978, ...,  0.09951452,
         0.08632279,  0.0892127 ]])