In [10]:
import numpy as np 
import pandas as pd

dict_ip = {'a':[0,0,2,1],'b':[0,1,0,1]}
dict_op = {'o':[0,1,1,0]}

#creating the dataframes for the ips and ops
xor_df = pd.DataFrame(dict_ip)
dict_op_df = pd.DataFrame(dict_op)

# transforming the dataframes into numpy arrays
xor = np.array(xor_df)
labels = np.array(dict_op_df)

In [16]:
xor/2.0

array([[ 0. ,  0. ],
       [ 0. ,  0.5],
       [ 1. ,  0. ],
       [ 0.5,  0.5]])

In [12]:
xor_df

a  b
0  0  0
1  0  1
2  2  0
3  1  1

In [13]:
xor*xor_df

a  b
0  0  0
1  0  1
2  4  0
3  1  1

In [2]:
#data = pd.read_csv('/home/achyutganti/Documents/myPython/ML Class/Neural_Ntwrk/train.csv')

In [87]:
labels

array([[0],
       [1],
       [1],
       [0]])

In [88]:
i_bias_unit = np.ones((len(xor),1))
i_bias_unit

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [89]:
h_bias_unit = np.ones((len(xor),1))
h_bias_unit

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [90]:
i_w = np.array([[1,0.5],[-1,2]])
i_w

array([[ 1. ,  0.5],
       [-1. ,  2. ]])

In [109]:
h_w = np.array([[1.5,-1]])
h_w

array([[ 1.5, -1. ]])

In [92]:
i_b_w = np.array([[1,1]])
i_b_w

array([[1, 1]])

In [93]:
o_b_w = np.array([[1]])
o_b_w

array([[1]])

In [94]:
hidden_unit_values = np.dot(np.c_[i_bias_unit,xor],np.c_[i_b_w.transpose(),i_w].transpose())
hidden_unit_values

array([[ 1. ,  1. ],
       [ 1.5,  3. ],
       [ 2. ,  0. ],
       [ 2.5,  2. ]])

In [95]:
sig_hidden = 1/(1+np.exp(-hidden_unit_values))
sig_hidden

array([[ 0.73105858,  0.73105858],
       [ 0.81757448,  0.95257413],
       [ 0.88079708,  0.5       ],
       [ 0.92414182,  0.88079708]])

In [96]:
out_value = np.dot(np.c_[h_bias_unit,sig_hidden],np.c_[o_b_w.transpose(),h_w].transpose())
out_value

array([[ 1.36552929],
       [ 1.27378759],
       [ 1.82119562],
       [ 1.50541565]])

In [97]:
total_out = 1/(1+np.exp(-out_value))
total_out

array([[ 0.79665688],
       [ 0.78139043],
       [ 0.86070953],
       [ 0.81838081]])

In [98]:
total_error = (labels-total_out)**2/2
total_error

array([[ 0.31733109],
       [ 0.02389507],
       [ 0.00970092],
       [ 0.33487358]])

In [99]:
out_error = total_out*(1-total_out)*(labels-total_out)
out_error

array([[-0.12905419],
       [ 0.03734276],
       [ 0.01669934],
       [-0.12163893]])

In [100]:
hidden_layr_err = sig_hidden*(1-sig_hidden)*h_w*out_error
hidden_layr_err

array([[-0.03806039,  0.02537359],
       [ 0.00835431, -0.00168702],
       [ 0.00262999, -0.00417484],
       [-0.01279101,  0.01277131]])

In [101]:
h_w = h_w+0.5*(sig_hidden*out_error)
h_w

array([[ 1.45282691, -1.04717309],
       [ 1.51526524, -0.98221413],
       [ 1.50735437, -0.99582516],
       [ 1.44379419, -1.05356961]])

In [105]:
i_w = i_w+0.5*np.dot(hidden_layr_err.transpose(),xor);
i_w

array([[ 0.99491949,  0.49778165],
       [-0.99570176,  2.00554214]])

In [80]:
A = np.dot(hidden_layr_err.T,xor)
B = 0.5*A
np.dot(i_w,B)
# i_w.shape

array([[-0.0029314 ,  0.00055272],
       [ 0.01367698,  0.01330264]])

In [123]:
np.dot(hidden_layr_err.transpose(),xor)+i_w

array([[ 0.98475846,  0.49334495],
       [-0.98710529,  2.01662643]])

In [113]:
np.dot(out_error.transpose(),sig_hidden)*0.5+h_w

array([[ 1.41924071, -1.07878198]])

In [124]:
i_bias_unit.shape

(4, 1)

In [129]:
yyyy = np.dot(hidden_layr_err.transpose(),i_bias_unit)
yyyy

array([[-0.03986711],
       [ 0.03228304]])

In [130]:
i_b_w.shape

(1, 2)

In [132]:
y2 = np.dot(i_bias_unit.transpose(),hidden_layr_err)
y2.shape


(1, 2)

In [3]:
dict_ip = {'a':[0,0,1,1],'b':[0,1,0,1]}
dict_op = {'o':[0,1,1,0]}

#creating the dataframes for the ips and ops
xor_df = pd.DataFrame(dict_ip)
dict_op_df = pd.DataFrame(dict_op)

# transforming the dataframes into numpy arrays
xor = np.array(xor_df)
labels = np.array(dict_op_df)

In [5]:
import random

In [5]:
def randomize(df,df_l):
    df2 = df.reindex(np.random.permutation(df.index))
    df_l2 = df_l.reindex(np.random.permutation(df_l.index))
    return df2, df_l2

In [13]:
for i in range(1,4):
    random.seed(i)
    d,l = randomize(xor_df,dict_op_df)
    print(d)
    print(l)

   a  b
0  0  0
2  1  0
3  1  1
1  0  1
   o
1  1
0  0
3  0
2  1
   a  b
3  1  1
0  0  0
2  1  0
1  0  1
   o
1  1
3  0
0  0
2  1
   a  b
3  1  1
1  0  1
2  1  0
0  0  0
   o
2  1
1  1
0  0
3  0


In [3]:
import random

In [23]:
random.seed(10)
d,l = randomize(xor_df,dict_op_df)
print(d)
print(l)

   a  b
1  0  1
2  1  0
3  1  1
0  0  0
   o
2  1
1  1
0  0
3  0
